name: push_to_staging
on: 
  workflow_dispatch:
    branches:
      - dev
      - master
      - main

jobs:
  upload_to_staging:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    # Check out the current branch
    - uses: actions/checkout@v2
      with:
        path: dev
    # Check out the staging barnch
    - uses: actions/checkout@v2
      with:
        path: staging
        repository: sabeechen/hgdb-dev-staging
    - run: |
          python3 staging/update.py dev staging
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
    - name: Publish Staging image
      uses: home-assistant/builder@master
      with:
        args: |
          --amd64 \
          --target dev/hassio-google-drive-backup
    - run: |
          cd staging
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Updating staging addon config"
          git push
